{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "nikt-link-proxy.fullname" . }}-config"
  labels:
    {{- include "nikt-link-proxy.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
{{- end }}